const data = {
  products: [
    {
      _id: 1,
      name: "Nike Shirt",
      category: "Shirts",
      image: "./images/p1.jpg",
      pice: 120,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "High quality product",
    },
    {
      _id: 2,
      name: "Adidas Shirt",
      category: "Shirts",
      image: "./images/p1.jpg",
      pice: 120,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      description: "High quality product",
    },
    {
      _id: 3,
      name: "Lacoste Shirt",
      category: "Shirts",
      image: "./images/p1.jpg",
      pice: 300,
      brand: "Lacoste",
      rating: 2.5,
      numReviews: 5,
      description: "High quality product",
    },
    {
      _id: 4,
      name: "Pants Adidas",
      category: "Pants",
      image: "./images/p1.jpg",
      pice: 80,
      brand: "Adidas",
      rating: 2.5,
      numReviews: 3,
      description: "High quality product",
    },
    {
      _id: 5,
      name: "Puma",
      category: "Pants",
      image: "./images/p1.jpg",
      pice: 80,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "High quality product",
    },
    {
      _id: 6,
      name: "Adidas Shirt",
      category: "Shirts",
      image: "./images/p1.jpg",
      pice: 350,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 20,
      description: "High quality product",
    },
  ],
};

export default data;
